services:
  # Backend service (API and core logic)
  nofx:
    image: docker.mxyhi.com/tinkle-community/nofx-trading:latest
    container_name: nofx-trading
    restart: unless-stopped
    ports:
      - "${NOFX_BACKEND_PORT:-8080}:8080"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./decision_logs:/app/decision_logs
      - /etc/localtime:/etc/localtime:ro # Sync host time
    environment:
      - TZ=${NOFX_TIMEZONE:-Asia/Shanghai} # Set timezone
    networks:
      - nofx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend service (static serving and proxy)
  nofx-frontend:
    image: docker.mxyhi.com/tinkle-community/nofx-frontend:latest
    container_name: nofx-frontend
    restart: unless-stopped
    ports:
      - "${NOFX_FRONTEND_PORT:-3000}:80"
    networks:
      - nofx-network
    depends_on:
      - nofx
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  nofx-network:
    driver: bridge
